spring:
  datasource:
    url: jdbc:mysql://localhost:13306/cloud_project?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: idaas_toa
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: "classpath*:/mapper/**/*.xml"

